---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
library(patchwork)
library(plotly)
library(p8105.datasets)

library(flexdashboard)
```

```{r}
data("ny_noaa")

ny_noaa_clean <- ny_noaa%>%
  drop_na(tmin,tmax,prcp,snow,snwd)%>%
  filter(id == 'USC00300023')%>%
  mutate(tmin = as.numeric(tmin),
         tmax = as.numeric(tmax))%>%
  separate(date, into = c("year", "month", "day"), convert = TRUE)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
#plotly scatterplot for maximum temp vs minimum temp
ny_noaa_clean %>% 
  plot_ly(x = ~tmin, y = ~tmax,
          type = 'scatter', mode = 'markers',alpha=0.7) %>%
  layout(
    title = "Scatter Plot of Maximum vs. Minimum Temperature",
    xaxis = list(title = "Minimum Temperature"),
    yaxis = list(title = "Maximum Temperature"))
```


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
#poly boxplot for yearly temperature range
ny_noaa_clean2 <- ny_noaa_clean %>%
  mutate(trange = tmax - tmin)

ny_noaa_clean2 %>%
  plot_ly(y = ~trange,x = ~year, type = "box", colors = "viridis")%>%
 layout(
    title = "Poly boxplot for yearly temperature range",
    xaxis = list(title = "Year"),
    yaxis = list(title = "Temperature Range"))
```

### Chart C

```{r}
#poly barchart for yearly total precipitation
ny_noaa_clean3 <- ny_noaa_clean%>%
  group_by(year)%>%
  summarise(total_prcp = sum(prcp))

ny_noaa_clean3%>%
  plot_ly(x=~year, y=~total_prcp,type="bar")%>%
   layout(
    title = "Poly barchart for total precipitation",
    xaxis = list(title = "Year"),
    yaxis = list(title = "Total precipitation"))
```

